server:
  http:
    addr: 0.0.0.0:8082
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9092
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:jinyubo@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
snowflake:
  start_time: "2025-12-27"
  machine_id: 1
registry:
  consul:
    address: 127.0.0.1:8500
    pass_deregister: http